apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: susana-shop  # ✅ Actualizado
spec:
  replicas: 1
  selector:
    matchLabels: { app: mysql }
  template:
    metadata:
      labels: { app: mysql }
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports: 
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              value: "tienda"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets  # ✅ Usar el mismo secret
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets  # ✅ Usar el mismo secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: init
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
          # ✅ Health checks añadidos
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: data
          persistentVolumeClaim: 
            claimName: mysql-pvc
        - name: init
          configMap:
            name: mysql-init-sql
            items:
              - key: init.sql
                path: init.sql
