apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: miweb
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword123
  MYSQL_DATABASE: tienda
  MYSQL_USER: admin
  MYSQL_PASSWORD: admin123