apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: susana-shop  # ✅ Actualizado
  labels:
    app: backend
spec:
  type: ClusterIP
  selector: 
    app: backend  # ✅ Debe coincidir con el deployment
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
